package org.apache.maven.BD;
// Generated 15 ene 2024, 12:28:38 by Hibernate Tools 6.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Provincias generated by hbm2java
 */
public class Provincias implements java.io.Serializable {

	private int id;
	private Comunidadesautonomas comunidadesautonomas;
	private String nombre;
	private String capital;
	private Integer poblacion;
	private BigDecimal superficieKm2;
	private Set puebloses = new HashSet(0);

	public Provincias() {
	}

	public Provincias(int id, Comunidadesautonomas comunidadesautonomas, String nombre, String capital,
			Integer poblacion, BigDecimal superficieKm2, Set puebloses) {
		this.id = id;
		this.comunidadesautonomas = comunidadesautonomas;
		this.nombre = nombre;
		this.capital = capital;
		this.poblacion = poblacion;
		this.superficieKm2 = superficieKm2;
		this.puebloses = puebloses;
	}

	public Provincias(int id) {
		super();
		this.id = id;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Comunidadesautonomas getComunidadesautonomas() {
		return this.comunidadesautonomas;
	}

	public void setComunidadesautonomas(Comunidadesautonomas comunidadesautonomas) {
		this.comunidadesautonomas = comunidadesautonomas;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCapital() {
		return this.capital;
	}

	public void setCapital(String capital) {
		this.capital = capital;
	}

	public Integer getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(Integer poblacion) {
		this.poblacion = poblacion;
	}

	public BigDecimal getSuperficieKm2() {
		return this.superficieKm2;
	}

	public void setSuperficieKm2(BigDecimal superficieKm2) {
		this.superficieKm2 = superficieKm2;
	}

	public Set getPuebloses() {
		return this.puebloses;
	}

	public void setPuebloses(Set puebloses) {
		this.puebloses = puebloses;
	}

}
