package org.apache.maven.BD;
// Generated 15 ene 2024, 12:28:38 by Hibernate Tools 6.3.1.Final

/**
 * Pueblos generated by hbm2java
 */
public class Pueblos implements java.io.Serializable {

	private int id;
	private Provincias provincias;
	private String nombre;
	private Integer poblacion;
	private String codigoPostal;
	private String coordenadasGeograficas;

	public Pueblos() {
	}

	public Pueblos(int id, Provincias provincias, String nombre, Integer poblacion, String codigoPostal,
			String coordenadasGeograficas) {
		this.id = id;
		this.provincias = provincias;
		this.nombre = nombre;
		this.poblacion = poblacion;
		this.codigoPostal = codigoPostal;
		this.coordenadasGeograficas = coordenadasGeograficas;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Provincias getProvincias() {
		return this.provincias;
	}

	public void setProvincias(Provincias provincias) {
		this.provincias = provincias;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Integer getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(Integer poblacion) {
		this.poblacion = poblacion;
	}

	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	public String getCoordenadasGeograficas() {
		return this.coordenadasGeograficas;
	}

	public void setCoordenadasGeograficas(String coordenadasGeograficas) {
		this.coordenadasGeograficas = coordenadasGeograficas;
	}

}
